import re
import sys
import numpy as np

#The purpose of this script is to get the coordinates of water molecules in
#*.xyz format from the molecular dynamic generated by deMon2k
#http://www.demon-software.com/public_html/program.html 

def getCoordinates(inputFile):

    F = open(inputFile,'r')
    #The input file is the general output of the software package deMon2k
    #http://www.demon-software.com/public_html/program.html 
    x = []
    y = []
    z = []
    Za = []
    step = 1 #Equivalent to the first step on the water dynamic
    for line in F:
        if "COORDINATES OF TIME STEP" in line:
            #print(step)
            # 30 is the total number of atmos, as we are training/testing with 10
            # waters molecules they are 30 atoms.
            k=1 #is the counter for the index of every atom
            j=1 #counter for a constant empty lines
            for j in range(4):#empty constant lines
                line = next(F)
            
            #positioned on line for atom 1 (counter k=1). Example for step 1:
            # 1  H        3.137918      0.417859     -0.908692       1     1.008

            for k in range(30): 
                Za.append(line.split()[1])
                x.append(float(line.split()[2])) #get x coordinate
                y.append(float(line.split()[3])) #get y coordinate
                z.append(float(line.split()[4])) #get z coordinate
                line=next(F)                   #jump to next atom

            step += 1 #when this loops ends, the outside loop search for the
                      #next step on the dynamic that's why step+=1
        
        if step > 6393:
            break

    nx = np.array(x)
    ny = np.array(y)
    nz = np.array(z)
    F.close()
    
    return nx, ny, nz, Za;





